# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CensusConnect
                                 A QGIS plugin
 This plugin downloads and joins census attribute data with census spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-27
        copyright            : (C) 2022 by Friendly Widgetmakers Society
        email                : stephen.francisco@temple.edu
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Friendly Widgetmakers Society'
__date__ = '2022-02-27'
__copyright__ = '(C) 2022 by Friendly Widgetmakers Society'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CensusConnect class from file CensusConnect.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .get_census import CensusConnectPlugin
    return CensusConnectPlugin()
